name: Migrate Docker Images

on:
  push:
    branches:
      - migrate

jobs:
  migrate-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Migrate images
        run: |
          for tag in nodejs18.x nodejs16.x nodejs14.x nodejs12.x; do
            docker pull turbopatent/docker-lambda:$tag
            docker tag turbopatent/docker-lambda:$tag ghcr.io/patentnavigation/docker-lambda:$tag
            docker push ghcr.io/patentnavigation/docker-lambda:$tag
          done
